### PR TITLE
change t-freeze calcualtion for sppt

### PR DESCRIPTION
**Pull request by pjpegion**
@jiandewang these changes were tested with the data-atmosphere stochastic physics regression test, and passed.

### CODE REVIEW

**Comment by jiandewang** [comment]
@pjpegion thanks for your quick work, can you combine your two commits log into one ? in general it is encouraged to use forced push to reduce minor commit (such as remove whitespace, et. al) to keep MOM6 log concise.

**Comment by pjpegion** [comment]
How do I do that?

**Comment by jiandewang** [comment]
git reset --soft HEAD~2
    git commit -m 'xxx'   
    git push --force  ......
    this will erase first two log, but use new commit message, still keep code change you made for the two commits

**Comment by pjpegion** [comment]
Thanks, that seemed to work

**Comment by jiandewang** [comment]
I just tried your code on GAEA but stochastic job failed to match current baseline.
Do you have access to GAEA ? if not I will repeat that on ORION as HERA is fully saturated

**Comment by pjpegion** [comment]
Yes, can you send me the path?  I would expect the baseline to change, and was surprised that it passed on hera. I can take a look at the output to see if the changes are within my expectations

**Comment by jiandewang** [comment]
logfile : /lustre/f2/dev/ncep/Jiande.Wang/MOM6-update/Phil-T-freeze/ufs-weather-model/tests/log_gaea.intel/run_025_datm_cdeps_stochy_gefs.log

run dir: /lustre/f2/scratch/Jiande.Wang/FV3_RT/rt_38860/datm_cdeps_stochy_gefs

let me know if you have permission issue

**Comment by pjpegion** [comment]
I cannot cd into /lustre/f2/scratch/Jiande.Wang.

**Comment by jiandewang** [comment]
can you try again ?

**Comment by jiandewang** [comment]
failed to match BL in ORION, too

**Comment by pjpegion** [comment]
I am puzzled.  I see differences in the restart file, but they are in tropical waters that are above freezing. Also,  the baseline on GAEA looks very different than the baseline on HERA, but the results from your regression test looks a lot like the baseline on hera.  I'll like to take a look at your orion result too.

**Comment by jiandewang** [comment]
/work/noaa/stmp/jiwang/stmp/jiwang/FV3_RT/rt_26223/datm_cdeps_stochy_gefs
you may need to wait for 5 minutes for me to do the chmod

**Comment by jiandewang** [comment]
when you say difference in restart file, which variable are you referring ?

**Comment by pjpegion** [comment]
I'm looking at temperature.

**Comment by jiandewang** [comment]
I gathered all restart file on HERA
/scratch1/NCEPDEV/climate/Jiande.Wang/working/MOM6-PHil-T-freeze/compare
but found HERA and ORION are identical

**Comment by pjpegion** [comment]
I just realized I wasted a bunch of time. The regression test does not pass on hera either. I was fooled by the last line in the log file:

Thu Aug 25 15:33:04 UTC 2022
Start Regression test

Compile 001 elapsed time 188 seconds. -DAPP=NG-GODAS -DMPI=ON -DCMAKE_BUILD_TYPE=Release -DMOM6SOLO=ON

baseline dir = /scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/develop-20220805/INTEL/datm_cdeps_stochy_gefs
working dir  = /scratch2/BMC/gsienkf/Philip.Pegion/stmp2/Philip.Pegion/FV3_RT/rt_200128/datm_cdeps_stochy_gefs
Checking test 001 datm_cdeps_stochy_gefs results ....
 Comparing RESTART/MOM.res.nc ............ALT CHECK......NOT OK
 Comparing RESTART/iced.2011-10-02-00000.nc ............ALT CHECK......NOT OK
 Comparing RESTART/DATM_GEFS_NEW.cpl.r.2011-10-02-00000.nc ............ALT CHECK......NOT OK

 0: The total amount of wall time                        = 153.114783
 0: The maximum resident set size (KB)                   = 962132

Test 001 datm_cdeps_stochy_gefs FAIL


REGRESSION TEST WAS SUCCESSFUL
Thu Aug 25 15:43:25 UTC 2022
Elapsed time: 00h:10m:23s. Have a nice day!


All three platforms have small coherent differences in areas where the water temperature is close to freezing, which is expected.  The larger differences that I was seeing seems to be an instability in the model that grows over times, which is just two solutions diverging since there are small differences earlier in the forecast.

**Comment by jiandewang** [comment]
puzzled solved, I am going to do the merging.

**Pull request merged**
